---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-backend
  namespace: keycloak
  labels:
     app: keycloak
spec:
  type: nodePort
  selector:
      app: keycloak
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 8443
      name: https
      targetport: 8443
    - port: 9090
      name: management
      targetPort: 9090
---  